### ISSUE TITLE
Error at docker-compose up

### ISSUE THREAD

**Issue by techhemant** [tobyqin/testcube#88]
~/test/testcube  master ✔                                                                                                         10d  ⍉
▶ docker-compose up
Building web
Step 1/11 : FROM python:3
 ---> a9d071760c82
Step 2/11 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> f78c57abb90c
Step 3/11 : RUN mkdir /code
 ---> Using cache
 ---> e007e8076015
Step 4/11 : WORKDIR /code
 ---> Using cache
 ---> e48ca1db0b26
Step 5/11 : ADD requirements.txt entrypoint.sh /code/
 ---> Using cache
 ---> 9cef7098ab77
Step 6/11 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> d47dff59350b
Step 7/11 : RUN chmod +x entrypoint.sh
 ---> Using cache
 ---> 6196247b5022
Step 8/11 : ADD . /code/
 ---> Using cache
 ---> 6850e1afe806
Step 9/11 : RUN chown -R $USER:$USER .
 ---> Using cache
 ---> 2b1d2bf19d84
Step 10/11 : RUN pip install testcube-client -U
 ---> Using cache
 ---> a70fe77e2665
Step 11/11 : RUN testcube-client --register http://0.0.0.0:4000
 ---> Running in 5099ad766946
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcbe30d2f98>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=4000): Max retries exceeded with url: /client-register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbe30d2f98>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/testcube-client", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/testcube_client/cli.py", line 107, in main
    register_client(args.register, args.force)
  File "/usr/local/lib/python3.7/site-packages/testcube_client/utils.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/testcube_client/request_helper.py", line 30, in register_client
    latest_version = get_server_version(register_url)
  File "/usr/local/lib/python3.7/site-packages/testcube_client/request_helper.py", line 19, in get_server_version
    response = requests.get(url)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=4000): Max retries exceeded with url: /client-register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbe30d2f98>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR: Service 'web' failed to build: The command '/bin/sh -c testcube-client --register http://0.0.0.0:4000' returned a non-zero code: 1

**Comment by tobyqin** [comment]
Hi @techhemant, there is an issue in docker file, it should not install client then register server, server is not ready at this moment, I had fixed it now you can pull the code again.

BTW,  to run with docker-compose you must have settings and related environment variables be ready at first, if you just want to try testcube with docker, use commands like below:

```
cd path/to/testcube
docker build -t testcube .
docker -d -p=4000:4000 testcube
# now visit testcube at http://localhost:4000
```
